### ISSUE TITLE
Error in AddToCart event

### ISSUE THREAD

**Issue by antoniogarcia78** [cadencelabs/m2-fbpixel#6]
Hi 
I use your plugin in a magento 2.1.4 In principle I had no problems but they tell me that the addToCart event fails.

With a simple product (without size) it works ok
content_type: product
content_ids: ["8433740575286"]
value: 14
currency: EUR
EVENT INFO
URL Called: Show
Load Time: 50.09 ms
Pixel Location: Show
Matched Products: 8433740575286

But with configurable products (with size) gives warning "WARNINGS
Can not match productsLearn more "
CUSTOM PARAMETERS SENT
content_type: product
content_ids: ["8433740564198"]
value: 49
currency: EUR
EVENT INFO
URL Called: Show
Load Time: 50.51 ms
Pixel Location: Show
Unmatched Products: 8433740564198

Very rare

Any news of this warning?

**Comment by Bashev** [comment]
This is not a problem of Pixel Tracker, this is with problem with Product feed which not send info about simple products as part of configurable.

**Comment by antoniogarcia78** [comment]
Closed
